name: bluebird 中文
description: Bluebird is a fully featured JavaScript promises library with unmatched performance.
url: "https://tuzhu008.github.io"
baseurl: "/bluebird_cn"
title: bluebird
timezone: Helsinki/Finland
highlighter: pygments
exclude:
  - Gemfile
  - Gemfile.lock
  - helpers.rb
defaults:
  - scope:
      path: docs
      type: pages
    values:
      layout: page
markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
version: 3.5.1
gems:
  - jekyll-redirect-from
destination: ../gh-pages/
keep_files:
  - .git
  - .gitignore
  - logo.png
  - CNAME
  - coverage
safe: false
encoding: utf-8
host: 0.0.0.0

